# Generated by Django 6.0.6 on 2026-06-10 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle / Bike', 'Motorcycle / Bike'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('EV', 'EV')], max_length=50)),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Tata', 'Tata'), ('Maruti Suzuki', 'Maruti Suzuki'), ('Hyundai', 'Hyundai'), ('Mahindra', 'Mahindra'), ('Royal Enfield', 'Royal Enfield')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('qr_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('society_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_conatct_number', models.CharField(max_length=15, null=True)),
                ('show_name', models.BooleanField(default=True, null=True)),
                ('show_city', models.BooleanField(default=False, null=True)),
                ('show_mobile', models.BooleanField(default=False, null=True)),
                ('show_email', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
