# Generated by Django 6.0.6 on 2026-06-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_add_vehicle_qr_id_qr_scan_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_scan_history',
            name='purpose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='qr_scan_history',
            name='scanner_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='qr_scan_history',
            name='scanner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
