# Generated by Django 6.0.6 on 2026-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_qr_scan_history_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='is_qr_generated',
            field=models.BooleanField(default=False),
        ),
    ]
