# Generated by Django 6.0.6 on 2026-06-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
