# Generated by Django 6.0.6 on 2026-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_create_at_notification_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='vehicle_color',
            new_name='vehicle_color_name',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_color_code',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
