# Generated by Django 6.0.6 on 2026-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_vehicle_color_add_vehicle_vehicle_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
