# Generated by Django 6.0.6 on 2026-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_show_society_qr_scan_history_scanner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='organization_type',
            field=models.CharField(choices=[('society', 'Society'), ('hospital', 'Hospital'), ('corporate', 'Corporate'), ('education', 'Educational Campus'), ('commercial', 'Commercial Complex')], default='society', max_length=20),
            preserve_default=False,
        ),
    ]
